CREATE DATABASE IF NOT EXISTS marketplace;
USE marketplace;

CREATE TABLE IF NOT EXISTS products (
id INT AUTO_INCREMENT PRIMARY KEY,
product_name VARCHAR(255) NOT NULL,
price INT NOT NULL,
quantity INT NOT NULL
);